# frozen_string_literal: true

source 'https://rubygems.org'

## https://github.com/bundler/bundler/issues/4978
git_source(:github) { |name| "https://github.com/#{name}.git" }

## system
# gem 'gorilla-patch'

## server
gem 'flame', github: 'AlexWayfer/flame'
# gem 'flame-flash', github: 'AlexWayfer/flame-flash'
gem 'puma'
# gem 'rack-slashenforce'
gem 'rack-utf8_sanitizer'
# gem 'rack_csrf', require: 'rack/csrf'

group :development do
	gem 'filewatcher'
	gem 'pry-byebug'
end

group :linter do
	# gem 'rubocop'
end

## database
# gem 'pg'
# gem 'sequel'
# gem 'sequel_pg', require: 'sequel'

## translations
# gem 'flame-r18n', github: 'AlexWayfer/flame-r18n'
## for named_variables filter
# gem 'r18n-rails-api'

## views
gem 'erubi', require: 'tilt/erubi'

## assets
# gem 'sass'

## others
# gem 'faker'
# gem 'google_currency'
# gem 'kramdown'
# gem 'mail'
# gem 'money'
# gem 'sentry-raven'

## tools
gem 'pry'
gem 'rack-console'
gem 'rake'
