# frozen_string_literal: true

source 'https://rubygems.org'

## system
# gem 'gorilla-patch'
# gem 'json'

## server
gem 'flame'
# gem 'flame-flash'
# gem 'flame-r18n'
gem 'puma'
# gem 'rack-slashenforce'
gem 'rack-utf8_sanitizer'

group :development do
	gem 'filewatcher'
	gem 'pry-byebug'
end

group :linter do
	# gem 'rubocop'
end

## database
# gem 'pg'
# gem 'sequel'
# gem 'sequel_pg', require: 'sequel'

## others
# gem 'faker'
# gem 'google_currency'
# gem 'kramdown'
# gem 'mail'
# gem 'money'
# gem 'sentry-raven'

## tools
gem 'pry'
gem 'rack-console'
gem 'rake'
