:environment: development
# :environment: production

:default: &default
  :binds:
    :tcp:
      :host: '0.0.0.0'
      :port: 3000
    # :unix: 'tmp/sockets/puma.sock'
  :daemonize: false
  :pids_dir: tmp/pids
  :logs_dir: log
  :pid_file: puma.pid
  # :workers_count: 1
  # :threads_count: 4

development: &development
  <<: *default
  :workers_count: 1
  :threads_count: 4

test: &test
  <<: *default
  :daemonize: false

production: &production
  <<: *default
  :binds:
    # :tcp:
    #   :host: '0.0.0.0'
    #   :port: 3000
    :unix: 'tmp/sockets/puma.sock'
