require:
  - rubocop-performance
  - rubocop-rspec

Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 2
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Lint/EmptyClass:
  Exclude:
    - spec/flame/require_dirs/**/*

RSpec/NestedGroups:
  Max: 6
## https://github.com/rubocop-hq/rubocop-rspec/pull/863/files#r471603667
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/FilePath:
  Exclude:
    - spec/integration/**/*
